Add pipeline(s) to start testing

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -25,6 +25,9 @@ orbs:
   eks: circleci/aws-eks@1.0.3
 
 executors:
+  base:
+    docker:
+      - image: cimg/base:2021.04
   runner:
     machine: true
     resource_class: circleci/k8s-test
@@ -59,12 +62,16 @@ workflows:
           context: custeng-aws
           requires:
             - install-helm-on-cluster-<< pipeline.git.revision >>
+      - approve-test:
+          type: approval
+          requires:
+            - install-runners-<< pipeline.git.revision >>
       - test-and-teardown:
           name: test-runners-<< pipeline.git.revision >>
           context:
             - circle-api
           requires:
-            - install-runners-<< pipeline.git.revision >>
+            - approve-test
 
   teardown:
     when: << pipeline.parameters.teardown >>
@@ -90,6 +97,49 @@ workflows:
 # Job Definitions #
 ###################
 jobs:
+  test-and-teardown:
+    executor: base
+    steps:
+      - run:
+          name: Trigger a pipeline
+          command: |
+            curl -u ${CIRCLE_TOKEN}: -X POST https://circleci.com/api/v2/project/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pipeline \
+              -H 'Content-Type: application/json' \
+              -H 'Accept: application/json' \
+              -d '{"branch": "'"${CIRCLE_BRANCH}"'", "parameters": {"main": false, "teardown": false, "test": true}}' > runner-pipeline.json
+            cat runner-pipeline.json
+
+      - run:
+          name: Poll pipeline's workflow, check its status every 5s
+          command: |-
+            pipeline_id=$(cat runner-pipeline.json | jq -r '.id')
+
+            while true; do
+              curl -u ${CIRCLE_TOKEN}: -X POST https://circleci.com/api/v2/pipeline/${pipeline_id}/workflow \
+                -H 'Content-Type: application/json' \
+                -H 'Accept: application/json' > runner-workflows.json \
+              cat runner-workflows.json
+              status=$(cat runner-workflows.json | jq -r '.items[0].status')
+
+              if [[ "$status" == "running" ]]; then
+                echo "Still running..."
+                sleep 5
+              else
+                if [[ "$status" == "success" ]]; then
+                  echo "Runner job succeeded" && exit 0
+                elif [[ "$status" =~ failed|failing|error|canceled ]]; then
+                  echo "Runner job failed" && exit 1
+                fi
+              fi
+            done
+      - run:
+          name: Call the cleanup workflow
+          command: |
+            curl -u ${CIRCLE_TOKEN}: -X POST https://circleci.com/api/v2/project/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pipeline \
+              -H 'Content-Type: application/json' \
+              -H 'Accept: application/json' \
+              -d '{"branch": "'"${CIRCLE_BRANCH}"'", "parameters": {"main": false, "teardown": true, "test": false}}'
+
   runner_job:
     executor: runner
     steps:
